# Generated by Django 5.0.6 on 2024-06-26 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.image'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.TimeField(),
        ),
    ]
