# Generated by Django 5.0.6 on 2024-06-26 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_variant_image_alter_categories_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='myapp.image'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.image'),
        ),
    ]
